# variables of deployment
appName: adservice
appReplicas: 1
appImage: gcr.io/google-samples/microservices-demo/adservice
appVersion: v0.6.0
containerPort: 9555
containerEnvVars:
- name: PORT
  value: "9555"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"

# variables of service
serviceType: ClusterIP
servicePort: 9555