# variables of deployment
appName: paymentservice
appReplicas: 1
appImage: gcr.io/google-samples/microservices-demo/paymentservice
appVersion: v0.2.3
containerPort: 50051
containerEnvVars:
- name: PORT
  value: "50051"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"

# variables of service
serviceType: ClusterIP
servicePort: 50051