# variables of deployment
appName: shippingservice
appReplicas: 1
appImage: gcr.io/google-samples/microservices-demo/shippingservice
appVersion: v0.6.0
containerPort: 50051
containerEnvVars:
- name: PORT
  value: "50051"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"

# variables of service
serviceType: ClusterIP
servicePort: 50051