# variables of deployment
appName: servicename
appReplicas: 1
appImage: 
appVersion: v1.0.0
containerPort: 8080
containerEnvVars:
- name: ENV_VAR_ONE
  value: "valueone"
- key: ENV_VAR_TWO
  name: "valuetwo"

# variables of service
serviceType: ClusterIP
servicePort: 8080