# variables of deployment
appName: currencyservice
appReplicas: 1
appImage: gcr.io/google-samples/microservices-demo/currencyservice
appVersion: v0.2.3
containerPort: 7000
containerEnvVars:
- name: PORT
  value: "7000"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"

# variables of service
serviceType: ClusterIP
servicePort: 7000