# variables of deployment
appName: productcatalogservice
appReplicas: 1
appImage: gcr.io/google-samples/microservices-demo/productcatalogservice
appVersion: v0.6.0
containerPort: 3550
containerEnvVars:
- name: PORT
  value: "3550"

# variables of service
serviceType: ClusterIP
servicePort: 3550